ConvertIncludeToRender:
  enabled: true

LiquidTag:
  enabled: true

MissingTemplate:
  enabled: true

NestedSnippet:
  enabled: true

RequiredLayoutThemeObject:
  enabled: true

SpaceInsideBraces:
  enabled: true

SyntaxError:
  enabled: true

TemplateLength:
  enabled: true
  max_length: 200

UnknownFilter:
  enabled: true

UnusedAssign:
  enabled: true

UnusedSnippet:
  enabled: true

MatchingSchemaTranslations:
  enabled: true

MatchingTranslations:
  enabled: true

DefaultLocale:
  enabled: true

TranslationKeyExists:
  enabled: true

ValidHTMLTranslation:
  enabled: true

ValidJson:
  enabled: true

ValidSchema:
  enabled: true

MissingRequiredTemplateFiles:
  enabled: true

UndefinedObject:
  enabled: true
